{% set name = "wbplot" %}
{% set version = "1.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dac3c34077c4f351bfa5d61554374afce17fb6d39c9337f16c2fef633c49d660

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - nibabel
    - numpy
    - pillow
    - python >={{ python_min }}

test:
  imports:
    - wbplot
    - wbplot.utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jbburt/wbplot
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "A package for automated plotting of neuroimaging maps using Connectome Workbench."

extra:
  recipe-maintainers:
    - SammedAdmuthe
